# Generated by Django 4.2.3 on 2023-07-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('question', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('poll_type', models.CharField(choices=[('mcq', 'Multiple Choice Question'), ('scq', 'Single Choice Question')], max_length=3)),
                ('options', models.JSONField(default=list)),
                ('votes', models.JSONField(default=list)),
            ],
        ),
    ]
